version: '3.8'  # Puedes usar otra versión compatible

services:
  mariadb:
    image: mariadb:latest  # Usa la última imagen de MariaDB
    container_name: mariadb_container  # Nombre del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Contraseña del usuario root
      MYSQL_DATABASE: DB1   # Nombre de la base de datos inicial
      MYSQL_USER: backendND                 # Nombre del usuario
      MYSQL_PASSWORD: Esp4nt0Esp4nt0*    # Contraseña del usuario
      MYSQL_ROOT_HOST: '172.18.0.1'
    
    volumes:
      - ./:/docker-entrypoint-initdb.d
    
    ports:
      - "3306:3306"  # Mapea el puerto 3306 del host al contenedor
    restart: always  # Reinicia automáticamente en caso de error o reinicio
